Thom440/LumberManagerWebEdition

- LumberManagerWebEdition/Data/ApplicationDbContext.cs
- LumberManagerWebEdition/Data/Migrations/20210408225829_Initial.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210408225829_Initial.cs
- LumberManagerWebEdition/LumberManagerWebEdition.csproj
- LumberManagerWebEdition/Models/Category.cs
- LumberManagerWebEdition/Models/Customer.cs
- LumberManagerWebEdition/Models/Order.cs
- LumberManagerWebEdition/Models/OrderLineItems.cs
- LumberManagerWebEdition/Models/Product.cs
> Created database

- LumberManagerWebEdition/Data/ApplicationDbContext.cs
- LumberManagerWebEdition/Data/Migrations/20210408231849_AddedSeedData.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210408231849_AddedSeedData.cs
> Added seed data to database

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/LumberManagerWebEdition.csproj
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Implemented Product index page

- LumberManagerWebEdition/Data/ProductDb.cs
> Created ProductDb with an async add method

- LumberManagerWebEdition/Views/Products/Create.cshtml
> Issue#21 add check boxes to create view

- LumberManagerWebEdition/Views/Products/Create.cshtml
> Aligned Checkboxes in a single row according to category

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/CategoryDb.cs
Closes #32
Closes #34
Also refactored ProductController to use CategoryDB
> Issue#32 create category db

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Products/UpdateInventory.cshtml
> Created Update view

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Views/Products/UpdateInventory.cshtml
> Got Update Inventory fully functional. Added GetProduct to ProductDb

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Issue#40 update product index page to show categories

- LumberManagerWebEdition/wwwroot/js/Create.js
> Fixed bug when CCA was not enabling WW when unchecked

- LumberManagerWebEdition/Views/Products/Delete.cshtml
> Implemented DELETE view for CRUD

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ApplicationDbContext.cs
- LumberManagerWebEdition/Data/Migrations/20210427202601_AddCategory.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210427202601_AddCategory.cs
> Issue#46 add category

- LumberManagerWebEdition/Data/ProductDb.cs
> Sorting is implemented in the products page

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Login.cshtml
- LumberManagerWebEdition/Areas/Identity/Pages/Account/Login.cshtml.cs
- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Models/IdentityHelper.cs
- LumberManagerWebEdition/Startup.cs
> Issue#49 implement roles

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Models/Product.cs
- LumberManagerWebEdition/Views/Products/UpdateInventory.cshtml
> Fixed bug in UpdateInventory, H,W,L no longer display 0 and hidden

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Views/Products/CustomerIndex.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Created CustomerIndex for customers to view products

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ProductDb.cs
> Implemented pagination in ProductDb and ProductController

- LumberManagerWebEdition/Views/Products/CustomerIndex.cshtml
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Navigation complete

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Products are no longer able to be duplicated in database.

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/CategoryDb.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Views/Products/CustomerIndex.cshtml
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Issue#57 implement filters

- LumberManagerWebEdition/Views/Products/CustomerIndex.cshtml
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Added bootstrap to index and customer index

- LumberManagerWebEdition/Controllers/ProductsController.cs
> Updated duplicate error message

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Implemented a shopping cart with cookies.

- LumberManagerWebEdition/Views/Products/Index.cshtml
> Deleted details link in Products page

- LumberManagerWebEdition/Views/Products/Index.cshtml
> Implemented a clear search button for the Products index page.

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Views/Cart/Summary.cshtml
> Implemented a View for the shopping cart.

- LumberManagerWebEdition/Controllers/CartController.cs
> Sorted cartProducts in CartController

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
- LumberManagerWebEdition/Models/ProductCookieHelper.cs
- LumberManagerWebEdition/Views/Cart/Summary.cshtml
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
> Users are now able to add multiples of a single item to the cart

- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Set up nav to Cart with cart icon for customer.

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
- LumberManagerWebEdition/Views/Cart/Summary.cshtml
> Implemented remove btn to delete products from cart.

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Implemented a count of product in the cart on the products page

- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
> Changed the temp quantity value from 0 to temp

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Data/ApplicationDbContext.cs
- LumberManagerWebEdition/Data/CategoryDb.cs
- LumberManagerWebEdition/Data/ProductDb.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
- LumberManagerWebEdition/Models/IdentityHelper.cs
- LumberManagerWebEdition/Models/Product.cs
- LumberManagerWebEdition/Models/ProductCookieHelper.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Products/UpdateInventory.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
- LumberManagerWebEdition/wwwroot/js/Create.js
> Documentation for everything public.

- LumberManagerWebEdition/Data/Migrations/20210709030018_BoardFeet.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210709030018_BoardFeet.cs
- LumberManagerWebEdition/Models/Product.cs
> Added board feet to product. Created new migration for board feet

- LumberManagerWebEdition.sln
- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/LumberManagerWebEdition.csproj
- LumberManagerWebEdition/Models/WeatherAPI.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- WeatherAPI/Program.cs
- WeatherAPI/WeatherAPI.csproj
> Implemented a weather API to the products page once user is logged in.

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
> Fixed weather icon not displaying

- LumberManagerWebEdition/Data/ProductDb.cs
> Fixed sorting of products

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Models/GetWeather.cs
- LumberManagerWebEdition/Startup.cs
> API is only called on startup

- LumberManagerWebEdition/Controllers/ProductsController.cs
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Moved weather to layout page

- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/css/site.css
> Fixed full sized window navbar adjustment.

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Data/Migrations/20210719185753_ChangeUserIdToString.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210719185753_ChangeUserIdToString.cs
- LumberManagerWebEdition/Data/OrderDB.cs
- LumberManagerWebEdition/Data/OrderLineItemsDB.cs
- LumberManagerWebEdition/Data/UserDB.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
- LumberManagerWebEdition/Models/User.cs
- LumberManagerWebEdition/Views/Cart/Confirm.cshtml
- LumberManagerWebEdition/Views/Cart/Submit.cshtml
- LumberManagerWebEdition/Views/Cart/Summary.cshtml
> Issue#91 create orders

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Data/OrderDB.cs
- LumberManagerWebEdition/Data/OrderLineItemsDB.cs
- LumberManagerWebEdition/Data/UserDB.cs
- LumberManagerWebEdition/Models/CookieHelper.cs
> Added documentation

- LumberManagerWebEdition/Views/Cart/Confirm.cshtml
> Added dollar sign and decimal places to total price.

- LumberManagerWebEdition/Data/ProductDb.cs
> Fixed sorting while filtering products

- LumberManagerWebEdition/Views/Products/Index.cshtml
> previousUrl now grabs the entire Url to preserve filtering

- LumberManagerWebEdition/LumberManagerWebEdition.csproj
- LumberManagerWebEdition/Properties/launchSettings.json
- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
> Manually entering quantity now updates properly

- LumberManagerWebEdition/Controllers/OrderController.cs
- LumberManagerWebEdition/Data/OrderDB.cs
- LumberManagerWebEdition/Data/OrderLineItemsDB.cs
- LumberManagerWebEdition/Data/UserDB.cs
- LumberManagerWebEdition/Views/Order/Index.cshtml
- LumberManagerWebEdition/Views/Order/ViewOrder.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
> Admin can now look up orders and view orders

- LumberManagerWebEdition/Controllers/CartController.cs
- LumberManagerWebEdition/Data/Migrations/20210725022251_ShipAddress.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210725022251_ShipAddress.cs
- LumberManagerWebEdition/Data/Migrations/20210725022958_ShippingContact.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210725022958_ShippingContact.cs
- LumberManagerWebEdition/Models/CreateOrderViewModel.cs
- LumberManagerWebEdition/Models/Order.cs
- LumberManagerWebEdition/Views/Cart/Confirm.cshtml
- LumberManagerWebEdition/Views/Order/ViewOrder.cshtml
Closes #157 
Closes #155 
Closes #154
> Customers can now set a shipping address on order creation

- LumberManagerWebEdition/Controllers/OrderController.cs
- LumberManagerWebEdition/Data/OrderDB.cs
- LumberManagerWebEdition/Views/Order/Index.cshtml
- LumberManagerWebEdition/wwwroot/js/OrderLookup.js
> Orders can now be looked up by order number

- LumberManagerWebEdition/Controllers/OrderController.cs
- LumberManagerWebEdition/Views/Order/Index.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Customers can now look up past orders

- LumberManagerWebEdition/Controllers/OrderController.cs
- LumberManagerWebEdition/Views/Order/Index.cshtml
> Orders can now be shipped the same day as order creation

- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
- LumberManagerWebEdition/wwwroot/css/site.css
> Fixed hamburger menu

- LumberManagerWebEdition/Controllers/ProductsController.cs
> Refactored ProductsController.Index()

- LumberManagerWebEdition/Data/OrderDB.cs
> Deleted Try/Catch from Order.DB/GetOrder. Existed for testing purposes.

- LumberManagerWebEdition/Views/Order/SetShipDate.cshtml
- LumberManagerWebEdition/wwwroot/css/dtsel.css
- LumberManagerWebEdition/wwwroot/js/CheckDate.js
- LumberManagerWebEdition/wwwroot/js/dtsel.js
> Added functional date picker for the ship date.

- LumberManagerWebEdition/Controllers/CartController.cs
> Refactored CartController Confirm into sub-methods.

- LumberManagerWebEdition/Views/Products/Create.cshtml
- LumberManagerWebEdition/wwwroot/js/Create.js
> Issue#185 implement board footage

- LumberManagerWebEdition/Views/Products/Index.cshtml
- LumberManagerWebEdition/wwwroot/js/AddToCart.js
> Moved y position from anchor to <script>

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Login.cshtml
> Removed prompts from login page.

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Register.cshtml
> Removed unnecessary prompts from Register page

- LumberManagerWebEdition/Controllers/HomeController.cs
- LumberManagerWebEdition/Views/Home/Privacy.cshtml
- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Deleted Privacy Page.

- LumberManagerWebEdition/Views/Home/Index.cshtml
> Deleted welcome message on home page.

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Register.cshtml
- LumberManagerWebEdition/Areas/Identity/Pages/Account/Register.cshtml.cs
- LumberManagerWebEdition/Data/Migrations/20210810041308_PhoneNumber.Designer.cs
- LumberManagerWebEdition/Data/Migrations/20210810041308_PhoneNumber.cs
- LumberManagerWebEdition/Models/IdentityHelper.cs
- LumberManagerWebEdition/Models/User.cs
> Issue#199 add phone number to register page

- LumberManagerWebEdition/Views/Order/ViewOrder.cshtml
> Added customer phone number below order date/ lined up ship date.

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
> Deleted two way authentication from account settings

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Manage/Email.cshtml
> Removed send verification e-mail link.

- LumberManagerWebEdition/Views/Shared/_Layout.cshtml
> Added spacing between city and temp for weather API.

- LumberManagerWebEdition/Areas/Identity/Pages/Account/Manage/Index.cshtml
- LumberManagerWebEdition/Areas/Identity/Pages/Account/Register.cshtml
- LumberManagerWebEdition/wwwroot/js/ValidatePhoneNumber.js
- LumberManagerWebEdition/wwwroot/js/ValidateProfilePhoneNumber.js
> Issue#208 add format validation for phone numbers

- LumberManagerWebEdition/Controllers/OrderController.cs
> Sold and OnHand quantities now adjust when order is shipped.
